travis:
  secure:
    BINSTAR_TOKEN: as9zhkHhuvclpop51CDZ2PBq+9vBEfn3VXO8JQijHFiKZHG2ViTO5H7/VRKRmY15aM80L6NtoWjM8oggq8VM0gvEP9Jp5ENaiDostsYnC9CUOizIAPSE4BhXst6KJH2QTtz/KGTieiRSA6gHaNgnAQEakk7Kq0+3ROMy3WJXjdNPLgjwywxzvS0EKqmg1+7qa/0zq/497u1LEd6caBy2ltzBGk1Db1Y8Le6WnPB0IoGuBO2I2UrUiWQkLt7AVL6J7YUc79/P2ND0x98iYyrFnd+z/BEA0AB/f73ItIjMfkPnsjXU7jJt+KoVjL30IdO2Ry2Uyf/rMOuhCg+dKDiS0hvbURummKUVus2Cqv0sx5B/HKDDNsPjggzplGIvI/lFZJvuzh76IaSZVCibyDIpIUim3n4bEvGW94mvLzDEf9CPXKoEH16TrBaT4HzzUJ9qviHuCo28yLWAIHrk0F9KJE4m6JLPPF2yxe47UvfxIOJc3XPCPGHXgywHAB8Vd19j6Za8d3TXcybkcigR6nuW6RtiVFvcGaP8Ulk7afJX03DGlT36QZcAxhceLDDbs1+SyFa+EcEtD2ziveVmbVFfm6B9l9lfNWhlNSiSLP4U2bC9UmeJWcR7TF8dztpoj4rZZIKzZCM5KPCl/PJFkVjPk1pKCiocyQ906Pd3fXTeTUM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
